### ISSUE TITLE
Bug on nav bar

### ISSUE THREAD

**Issue by Sicilat** [Huntears/photographie#19]
A little problem with the text, see file droped

![capture d ecran de 2018-11-13 22-35-38](https://user-images.githubusercontent.com/44788236/48444590-a7ba9880-e794-11e8-8113-3b5898a9d103.png)

**Comment by EliottDvx** [comment]
I don't see this pb. Try again with the new files uploaded.

**Comment by Sicilat** [comment]
Bug not present anymore, bug ticket marked as closed
