### ISSUE TITLE
Nav bar : When clicked on sub-menu container, it keep open even when the mouse is at another place

### ISSUE THREAD

**Issue by Sicilat** [Huntears/photographie#21]
![capture d ecran de 2018-11-13 22-43-37](https://user-images.githubusercontent.com/44788236/48444982-bd7c8d80-e795-11e8-8e7d-84b208d0f902.png)

**Comment by EliottDvx** [comment]
Minor problem which can be considered as a feature.

**Comment by EliottDvx** [comment]
Corrected without doing it on purpose
